--- #YAML:1.0
name:                WWW-TarPipe
version:             0.01
abstract:            An interface to tarpipe.com's REST based web service.
license:             perl
author:              
    - Andy Armstrong <andy@hexten.net>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    LWP::UserAgent:                0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
